Runs pre-commit on all files
Only manual intervention was correcting a typo in test.txt which was pointed out
by pre-commit. I made my correction, ran `git add -u` to updated, and then made
my commit. Full output below:

>> pre-commit run --all-files
style-files..............................................................Failed
- hook id: style-files
- files were modified by this hook

Styling  1  files:
 app.R ℹ
────────────────────────────────────────
Status	Count	Legend
✔ 	0	File unchanged.
ℹ 	1	File changed.
✖ 	0	Styling threw an error.
────────────────────────────────────────
Please review the changes carefully!

spell-check..............................................................Failed
- hook id: spell-check
- exit code: 1

The following spelling errors were found:
  WORD      FOUND IN
speling   text.txt:1
All spelling errors found were copied to inst/WORDLIST assuming they were not spelling errors and will be ignored in the future. Please  review the above list and for each word that is an actual typo:
 - fix it in the source code.
 - remove it again manually from inst/WORDLIST to make sure it's not
   ignored in the future.
 Then, try committing again.
Error: Spell check failed

Execution halted
readme-rmd-rendered..................................(no files to check)Skipped
parsable-R...............................................................Passed
no-browser-statement.....................................................Passed
Check for added large files..............................................Passed
Fix End of Files.........................................................Passed
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted python_example.py
All done! ✨ 🍰 ✨
1 file reformatted.

Don't commit common R artifacts......................(no files to check)Skipped